# Generated by Django 4.2 on 2024-02-24 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('8to9', '8am-9am'), ('9to10', '9am-10am'), ('10to11', '10am-11am'), ('11to12', '11am-12pm'), ('2to3', '2pm-3pm'), ('3to4', '3pm-4pm'), ('4to5', '4pm-5pm'), ('5to6', '5pm-6pm'), ('6to7', '6pm-7pm'), ('7to8', '7pm-8pm'), ('8to9_evening', '8pm-9pm'), ('9to10_evening', '9pm-10pm')], max_length=20)),
                ('reserved_for', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pitch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
