# Generated by Django 4.2 on 2024-07-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pitch_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('8to9', '8am-9am'), ('9to10', '9am-10am'), ('10to11', '10am-11am'), ('11to12', '11am-12pm'), ('2to3', '2pm-3pm'), ('3to4', '3pm-4pm'), ('4to5', '4pm-5pm'), ('5to6', '5pm-6pm'), ('6to7', '6pm-7pm'), ('7to8', '7pm-8pm'), ('8to9_evening', '8pm-9pm'), ('9to10_evening', '9pm-10pm')], default='8to9', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
    ]
