# Generated by Django 4.2 on 2024-07-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reservation_time_slot_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_for',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time_slot',
            new_name='time',
        ),
    ]
